services:
  - type: web
    name: sistema-alunos-api
    runtime: image
    image: maven:3.8.6-openjdk-17
    plan: free
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: PORT
        value: 10000
