# Nome da aplicação
spring.application.name=sistema-alunos-api

# Porta que o Spring vai escutar (o Render injeta a variável PORT automaticamente)
server.port=${PORT:8080}

# Configuração para não mostrar logs muito verbosos no console
logging.level.org.springframework=INFO
